[package]
name = "jigglefab"
version = "0.1.0"
edition = "2021"
default-run = "jigglefab-bin"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "jigglefab-bin"
path = "src/main.rs"

[[bin]]
name = "bench"
path = "src/bin/bench.rs"
test = false
bench = false

[[bin]]
name = "gen_chains"
path = "src/bin/gen_chains.rs"
test = false
bench = false

[[bin]]
name = "gen_wire_chains"
path = "src/bin/gen_wire_chains.rs"
test = false
bench = false

[dependencies]
wgpu = "23"
winit = "0.30"
glam = { version = "0.29", features = ["bytemuck"] }
bytemuck = { version = "1.16", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
anyhow = "1"
log = "0.4"
web-time = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.3"
env_logger = "0.11"
rayon = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "=0.2.95"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
console_log = "1"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlCanvasElement", "Window", "Location"] }
js-sys = "0.3"

[dev-dependencies]
serde_json = "1"

[profile.release]
opt-level = 3
lto = "thin"
