name:                chains
version:             0.1.0.0
github:              "githubuser/chains"
license:             BSD3
author:              "Andrew McKnight"
maintainer:          "thedonk@gmail.com"
copyright:           "2021 Andrew McKnight"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/chains#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - gloss
    - containers
    - mtl
    - random
    - vector
    - ilist
    - geo2d

executables:
  chains-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chains

tests:
  chains-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chains
    - geo2d
    - hspec
    - QuickCheck
