[meta]
name = "30-bead vertical chain"
chemistry = "grey"
seed = 42

[[bead]]
state = "grey"
pos = [15.0, 5.000]
[[bead]]
state = "grey"
pos = [15.0, 5.667]
[[bead]]
state = "grey"
pos = [15.0, 6.334]
[[bead]]
state = "grey"
pos = [15.0, 7.001]
[[bead]]
state = "grey"
pos = [15.0, 7.668]
[[bead]]
state = "grey"
pos = [15.0, 8.335]
[[bead]]
state = "grey"
pos = [15.0, 9.002]
[[bead]]
state = "grey"
pos = [15.0, 9.669]
[[bead]]
state = "grey"
pos = [15.0, 10.336]
[[bead]]
state = "grey"
pos = [15.0, 11.003]
[[bead]]
state = "grey"
pos = [15.0, 11.670]
[[bead]]
state = "grey"
pos = [15.0, 12.337]
[[bead]]
state = "grey"
pos = [15.0, 13.004]
[[bead]]
state = "grey"
pos = [15.0, 13.671]
[[bead]]
state = "grey"
pos = [15.0, 14.338]
[[bead]]
state = "grey"
pos = [15.0, 15.005]
[[bead]]
state = "grey"
pos = [15.0, 15.672]
[[bead]]
state = "grey"
pos = [15.0, 16.339]
[[bead]]
state = "grey"
pos = [15.0, 17.006]
[[bead]]
state = "grey"
pos = [15.0, 17.673]
[[bead]]
state = "grey"
pos = [15.0, 18.340]
[[bead]]
state = "grey"
pos = [15.0, 19.007]
[[bead]]
state = "grey"
pos = [15.0, 19.674]
[[bead]]
state = "grey"
pos = [15.0, 20.341]
[[bead]]
state = "grey"
pos = [15.0, 21.008]
[[bead]]
state = "grey"
pos = [15.0, 21.675]
[[bead]]
state = "grey"
pos = [15.0, 22.342]
[[bead]]
state = "grey"
pos = [15.0, 23.009]
[[bead]]
state = "grey"
pos = [15.0, 23.676]
[[bead]]
state = "grey"
pos = [15.0, 24.343]
